diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=isabelnieto900
user.email=linietop@udistrital.edu.co
credential.helper=manager
safe.directory=C:/Users/laura/Downloads/proyectoC
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/camilohuertas02/Simulacion-Gravitacional-N-Cuerpos.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
user.name=isabelnieto900
user.mail=linietop@udistrital.edu.co
branch.prueba-acceso.vscode-merge-base=origin/main
branch.prueba-acceso.vscode-merge-base=origin/main
branch.prueba-acceso.vscode-merge-base=origin/main
branch.prueba-acceso.remote=origin
branch.prueba-acceso.merge=refs/heads/prueba-acceso
branch.prueba2.vscode-merge-base=origin/prueba-acceso
